---
title: "R Notebook"
output: html_notebook
---

Descripción
La sepsis ocasiona en el mundo más de mil muertes cada día, muchos de estos pacientes
adquieren la infección estando hospitalizados y constituye la complicación intrahospitalaria más
frecuente. La infección de pacientes por las manos contaminadas del personal de salud es una de
las formas de diseminación de los agentes infecciosos. La higiene de las manos es el factor
individual más importante para el control de las infecciones, es difícil entender que un hecho tan
rutinario en la práctica de la medicina, como lavarse las manos previo a examinar a un paciente,
haya causado tanta controversia en la época de 1800.
A principios de la década de 1840 se descubrió una enfermedad mortal que afectaba a las
mujeres que acababan de dar a luz, cerca del 10% de las mujeres morían a causa de esta
enfermedad y el origen provenía de las manos contaminadas del personal médico que atendía
los partos.
En este proyecto, vamos a analizar los datos que demuestran la importancia del lavado de
manos, identificando anomalías en los procedimientos médicos


1. Conociendo los datos
1.1. Cargue el paquete tidyverse.
1.2. Lea el archivo deaths_handwashing.csv usando read_csv y asígnelo a la variable yearly.
1.3. Imprima la variable yearly.

```{r}
library (tidyverse)
yearly <- read.csv("deaths_handwashing.csv", header = TRUE, sep = ",", quote = "\"", dec = ".", fill = TRUE, comment.char = "", encoding = "unknown")
yearly

```

